/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import java.text.*;
import java.awt.print.*;
import javax.swing.JTable;

/**
 *
 * @author JamilahLKM
 */
public class laporan extends javax.swing.JFrame {
    Statement st;
    ResultSet rs;
    Connection cn = koneksi.koneksi.getKoneksi();
    public static String iduser;
    public int mas,kel;
    public DefaultTableModel tabModel;
 
    /**
     * Creates new form laporan
     */
    public void judul(){
        Object[] judul = {"ID","Tanggal","Waktu","Uraian Keuangan","Pemasukan","Pengeluaran"};
        tabModel = new DefaultTableModel(null, judul);
        tbl_uang.setModel(tabModel);
    }
    
    public void tampildata(){
        try {
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tbl_keuangan WHERE id_user = '"+iduser+"' ORDER BY status ASC");
            while(rs.next()){
                Object[] data = {
                    rs.getInt("id"),
                    rs.getDate("tanggal"),
                    rs.getTimestamp("waktu"),
                    rs.getString("keterangan"),
                    rs.getInt("masuk"),
                    rs.getInt("keluar")
                };
                tabModel.addRow(data);
            }
        } catch (Exception e) {
        }
    }
    
    public void masuk(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT SUM(masuk) as 'mas' FROM tbl_keuangan WHERE id_user = '"+iduser+"'");
            rs.next();
            mas = rs.getInt(1);
            String a = String.valueOf(mas);
            a = a.replace(".", "");
            a = NumberFormat.getNumberInstance(Locale.ENGLISH).format(Double.parseDouble(a));
            a = a.replace(",", ".");
            lmasuk.setText("Rp. "+a);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void keluar(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT SUM(keluar) as 'klr' FROM tbl_keuangan WHERE id_user = '"+iduser+"'");
            rs.next();
            kel = rs.getInt(1);
            String a = String.valueOf(kel);
            a = a.replace(".", "");
            a = NumberFormat.getNumberInstance(Locale.ENGLISH).format(Double.parseDouble(a));
            a = a.replace(",", ".");
            lkeluar.setText("Rp. "+a);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void saldo(){
        int c = mas -kel;
        String sal = String.valueOf(c);
        sal = sal.replace(".", "");
        sal = NumberFormat.getNumberInstance(Locale.ENGLISH).format(Double.parseDouble(sal));
        sal = sal.replace(",", ".");
        lsaldo.setText("Rp. "+sal);   
    }
    
    public laporan() {
        initComponents();
        judul();
        tampildata();
        masuk();
        keluar();
        saldo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_uang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lsaldo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lkeluar = new javax.swing.JLabel();
        lmasuk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_uang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_uang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 1000, 330));

        jLabel2.setBackground(new java.awt.Color(44, 62, 80));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(189, 195, 199));
        jLabel2.setText("Total Pengeluaran  :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, -1, -1));

        jLabel1.setBackground(new java.awt.Color(44, 62, 80));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(189, 195, 199));
        jLabel1.setText("Laporan Keuangan Anda");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel3.setBackground(new java.awt.Color(44, 62, 80));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(189, 195, 199));
        jLabel3.setText("Saldo Akhir              :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, -1, -1));

        lsaldo.setBackground(new java.awt.Color(44, 62, 80));
        lsaldo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lsaldo.setForeground(new java.awt.Color(189, 195, 199));
        lsaldo.setText("Rp. 100.000.000");
        jPanel1.add(lsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 560, -1, -1));

        jButton2.setBackground(new java.awt.Color(136, 0, 0));
        jButton2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton2.setText("X");
        jButton2.setAlignmentX(0.5F);
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 70, 40));

        jButton3.setBackground(new java.awt.Color(189, 195, 199));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(44, 62, 80));
        jButton3.setText("KEMBALI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 210, 150, 60));

        jButton4.setBackground(new java.awt.Color(189, 195, 199));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(44, 62, 80));
        jButton4.setText("CETAK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 140, 150, 60));

        jLabel5.setBackground(new java.awt.Color(44, 62, 80));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(189, 195, 199));
        jLabel5.setText("Total Pemasukan    :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, -1));

        lkeluar.setBackground(new java.awt.Color(44, 62, 80));
        lkeluar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lkeluar.setForeground(new java.awt.Color(189, 195, 199));
        lkeluar.setText("Rp. 100.000.000");
        jPanel1.add(lkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 520, -1, -1));

        lmasuk.setBackground(new java.awt.Color(44, 62, 80));
        lmasuk.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lmasuk.setForeground(new java.awt.Color(189, 195, 199));
        lmasuk.setText("Rp. 100.000.000");
        jPanel1.add(lmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Laporan Pemasukan KEUANGAN");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            tbl_uang.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        iduser=args[0];
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lkeluar;
    private javax.swing.JLabel lmasuk;
    private javax.swing.JLabel lsaldo;
    private javax.swing.JTable tbl_uang;
    // End of variables declaration//GEN-END:variables
}
