/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author JamilahLKM
 */
public class login extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
    public Connection cn = koneksi.koneksi.getKoneksi();
    public String jk;
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        buttonGroup1.add(cl);
        buttonGroup1.add(cp);
        ssignup.setVisible(false);
        slogin.setVisible(true);
        psignup.setVisible(false);
        plogin.setVisible(true);
        tuser.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        ssignup = new javax.swing.JSeparator();
        slogin = new javax.swing.JSeparator();
        up = new javax.swing.JButton();
        in = new javax.swing.JButton();
        plogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        blogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tuser = new javax.swing.JTextField();
        tpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        psignup = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        up_nama = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        up_user = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        up_pass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        cp = new javax.swing.JRadioButton();
        bdaftar = new javax.swing.JButton();
        cl = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(189, 195, 199));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(44, 62, 80));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(44, 62, 80));
        jLabel2.setText("Manage Your finances!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel1.setBackground(new java.awt.Color(44, 62, 80));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 62, 80));
        jLabel1.setText("For Your Future.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(210, 77, 87));
        jButton1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton1.setText("X");
        jButton1.setAlignmentX(0.5F);
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 60, 40));

        ssignup.setBackground(new java.awt.Color(210, 77, 87));
        ssignup.setForeground(new java.awt.Color(210, 77, 87));
        jPanel1.add(ssignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 350, 10));

        slogin.setBackground(new java.awt.Color(210, 77, 87));
        slogin.setForeground(new java.awt.Color(210, 77, 87));
        jPanel1.add(slogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 350, 10));

        up.setBackground(new java.awt.Color(189, 195, 199));
        up.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        up.setForeground(new java.awt.Color(189, 195, 199));
        up.setText("SIGN UP");
        up.setBorderPainted(false);
        up.setContentAreaFilled(false);
        up.setFocusPainted(false);
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        jPanel1.add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 350, 60));

        in.setBackground(new java.awt.Color(189, 195, 199));
        in.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        in.setForeground(new java.awt.Color(189, 195, 199));
        in.setText("SIGN IN");
        in.setBorderPainted(false);
        in.setContentAreaFilled(false);
        in.setFocusPainted(false);
        in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inActionPerformed(evt);
            }
        });
        jPanel1.add(in, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 350, 60));

        plogin.setBackground(new java.awt.Color(44, 62, 80));
        plogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(189, 195, 199));
        jLabel3.setText("username");
        plogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        blogin.setBackground(new java.awt.Color(189, 195, 199));
        blogin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        blogin.setForeground(new java.awt.Color(44, 62, 80));
        blogin.setText("SIGN IN");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        plogin.add(blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 570, 70));
        plogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 570, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(189, 195, 199));
        jLabel5.setText("password");
        plogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));
        plogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 570, 30));

        tuser.setBackground(new java.awt.Color(44, 62, 80));
        tuser.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        tuser.setForeground(new java.awt.Color(189, 195, 199));
        tuser.setBorder(null);
        tuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tuserFocusGained(evt);
            }
        });
        tuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tuserMouseClicked(evt);
            }
        });
        plogin.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 570, 50));

        tpass.setBackground(new java.awt.Color(44, 62, 80));
        tpass.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        tpass.setForeground(new java.awt.Color(189, 195, 199));
        tpass.setBorder(null);
        plogin.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 570, 50));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(189, 195, 199));
        jLabel4.setText("SIGN IN WITH YOUR ACCOUNT");
        plogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jPanel1.add(plogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 700, 500));

        psignup.setBackground(new java.awt.Color(44, 62, 80));
        psignup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(189, 195, 199));
        jLabel7.setText("Your Email");
        psignup.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(189, 195, 199));
        jLabel8.setText("Your Gender");
        psignup.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        up_nama.setBackground(new java.awt.Color(44, 62, 80));
        up_nama.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        up_nama.setForeground(new java.awt.Color(189, 195, 199));
        up_nama.setBorder(null);
        up_nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                up_namaFocusGained(evt);
            }
        });
        up_nama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up_namaMouseClicked(evt);
            }
        });
        psignup.add(up_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 640, 50));
        psignup.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 640, 10));
        psignup.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 640, 10));

        up_user.setBackground(new java.awt.Color(44, 62, 80));
        up_user.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        up_user.setForeground(new java.awt.Color(189, 195, 199));
        up_user.setBorder(null);
        up_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                up_userFocusGained(evt);
            }
        });
        up_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up_userMouseClicked(evt);
            }
        });
        psignup.add(up_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 640, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(189, 195, 199));
        jLabel9.setText("Your Password");
        psignup.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        psignup.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 640, 10));

        up_pass.setBackground(new java.awt.Color(44, 62, 80));
        up_pass.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        up_pass.setForeground(new java.awt.Color(189, 195, 199));
        up_pass.setBorder(null);
        psignup.add(up_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 640, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(189, 195, 199));
        jLabel10.setText("Your Name");
        psignup.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        cp.setBackground(new java.awt.Color(44, 62, 80));
        cp.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cp.setForeground(new java.awt.Color(189, 195, 199));
        cp.setText("FEMALE");
        cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpActionPerformed(evt);
            }
        });
        psignup.add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        bdaftar.setBackground(new java.awt.Color(189, 195, 199));
        bdaftar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bdaftar.setForeground(new java.awt.Color(44, 62, 80));
        bdaftar.setText("SIGN UP");
        bdaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdaftarActionPerformed(evt);
            }
        });
        psignup.add(bdaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 640, 70));

        cl.setBackground(new java.awt.Color(44, 62, 80));
        cl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cl.setForeground(new java.awt.Color(189, 195, 199));
        cl.setText("MALE");
        cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clActionPerformed(evt);
            }
        });
        psignup.add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(189, 195, 199));
        jLabel6.setText("JOIN WITH ME AND CREATE YOUR ACCOUNT");
        psignup.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jPanel1.add(psignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 690, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 960, 740));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 350)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(104, 195, 163));
        jLabel11.setText("$");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        // TODO add your handling code here:
        if(tuser.getText().isEmpty() || tpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "LENGKAPi DATA !");
            tuser.requestFocus();
        }else{
            try {
                st =cn.createStatement();
                rs = st.executeQuery("SELECT * FROM tbl_user");
                String user,pass;
                int a = 0;
                while (rs.next()) {                    
                    user = rs.getString("username");
                    pass = rs.getString("password");
                    if(tuser.getText().equals(user) && tpass.getText().equals(pass)){
                        JOptionPane.showMessageDialog(null, "LOGIN BERHASIL !");
                        String tmp_id[] = new String[1];
                        tmp_id[0] = tuser.getText();
                        utama.main(tmp_id);
                        this.setVisible(false);
                        a++;
                    }
                }
                if(a == 0){
                    JOptionPane.showMessageDialog(null, "USERNAME atau PASSWORD Anda salah");
                    tuser.setText("");
                    tuser.requestFocus();
                    tpass.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_bloginActionPerformed

    private void tuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tuserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserFocusGained

    private void tuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tuserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserMouseClicked

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
       plogin.setVisible(false);
       psignup.setVisible(true);
        ssignup.setVisible(true);
        slogin.setVisible(false);
       up_user.requestFocus();
    }//GEN-LAST:event_upActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    private void clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clActionPerformed
        // TODO add your handling code here:
        jk = "Male";
    }//GEN-LAST:event_clActionPerformed

    private void cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpActionPerformed
        // TODO add your handling code here:
        jk = "Female";
    }//GEN-LAST:event_cpActionPerformed

    private void up_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up_userMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_up_userMouseClicked

    private void up_userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_up_userFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_up_userFocusGained

    private void bdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdaftarActionPerformed
        // TODO add your handling code here:
        if (up_user.getText().isEmpty() || up_pass.getText().isEmpty() || up_nama.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA ANDA !");
              up_user.requestFocus();
        }else if(cl.isSelected() == false && cp.isSelected() == false){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA ANDA !");
            
        }else{
            try {
                st = cn.createStatement();
                st.executeUpdate("INSERT INTO tbl_user VALUES ('"+up_user.getText()+"','"+up_pass.getText()+"','"+up_nama.getText()+"','"+jk+"')");
                JOptionPane.showMessageDialog(null, "SIGN UP SUCCESS");
                plogin.setVisible(true);
                psignup.setVisible(false);
                tuser.setText(up_user.getText());
                ssignup.setVisible(false);
                slogin.setVisible(true);
                up_user.setText("");
                up_pass.setText("");
                up_nama.setText("");
                buttonGroup1.clearSelection();
                tpass.requestFocus();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_bdaftarActionPerformed

    private void up_namaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up_namaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_up_namaMouseClicked

    private void up_namaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_up_namaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_up_namaFocusGained

    private void inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inActionPerformed
        // TODO add your handling code here:
        plogin.setVisible(true);
        psignup.setVisible(false);
        ssignup.setVisible(false);
        slogin.setVisible(true);
        tuser.requestFocus();
    }//GEN-LAST:event_inActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdaftar;
    private javax.swing.JButton blogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cl;
    private javax.swing.JRadioButton cp;
    private javax.swing.JButton in;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel plogin;
    private javax.swing.JPanel psignup;
    private javax.swing.JSeparator slogin;
    private javax.swing.JSeparator ssignup;
    private javax.swing.JPasswordField tpass;
    public javax.swing.JTextField tuser;
    private javax.swing.JButton up;
    private javax.swing.JTextField up_nama;
    private javax.swing.JPasswordField up_pass;
    private javax.swing.JTextField up_user;
    // End of variables declaration//GEN-END:variables
}
