/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javafx.scene.layout.Background;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JamilahLKM
 */
public class pemasukan extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel; 
    public Connection cn = koneksi.koneksi.getKoneksi();
    public static String iduser;
    java.util.Date date = new java.util.Date();
    SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-d");
    public String tgl = format.format(date);
    public int mas;
    
    public void masuk(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT SUM(masuk) as 'mas' FROM tbl_keuangan WHERE id_user = '"+iduser+"'");
            rs.next();
            mas = rs.getInt(1);
            String a = String.valueOf(mas);
            a = a.replace(".", "");
            a = NumberFormat.getNumberInstance(Locale.ENGLISH).format(Double.parseDouble(a));
            a = a.replace(",", ".");
            lmasuk.setText("Rp. "+a);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
      public void judul(){
        Object[] judul = {"ID","Tanggal","Waktu","Uraian Pemasukan","Jumlah"};
        tabModel = new DefaultTableModel(null,judul);
        tbl_masuk.setModel(tabModel);
    }
    
    public void tampildata(){
        try {
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tbl_keuangan WHERE status ='pemasukan' AND id_user = '"+iduser+"' ORDER BY id ASC");
            while (rs.next()) {                
                 Object[] data = {
                        rs.getInt("id"),
                        rs.getDate("tanggal"),
                        rs.getTime("waktu"),
                        rs.getString("keterangan"),
                        rs.getInt("masuk")
                    };
                    tabModel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void reset(){
        ttanggal.setText(tgl);
        tketerangan.setText("");
        tjumlah.setText("");
        tketerangan.requestFocus();
        bedit.setEnabled(false);
        bhapus.setEnabled(false);
        bsimpan.setEnabled(true);
    }
    
  
    /**
     * Creates new form pemasukan
     */
    public pemasukan() {
        initComponents();
        judul();
        tampildata();
        reset();
        masuk();
        bsimpan.setEnabled(true);
        ttanggal.setText(tgl);
        tketerangan.requestFocus();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ttanggal = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tketerangan = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tjumlah = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        bkembali = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_masuk = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lmasuk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(44, 62, 80));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(189, 195, 199));
        jLabel1.setText("FORM INPUT PEMASUKAN KEUANGAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        ttanggal.setEditable(false);
        ttanggal.setBackground(new java.awt.Color(44, 62, 80));
        ttanggal.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        ttanggal.setForeground(new java.awt.Color(189, 195, 199));
        ttanggal.setBorder(null);
        ttanggal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ttanggalFocusGained(evt);
            }
        });
        ttanggal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttanggalMouseClicked(evt);
            }
        });
        ttanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ttanggalKeyReleased(evt);
            }
        });
        jPanel1.add(ttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 200, 50));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 1220, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 200, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(189, 195, 199));
        jLabel2.setText("Tanggal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        tketerangan.setBackground(new java.awt.Color(44, 62, 80));
        tketerangan.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        tketerangan.setForeground(new java.awt.Color(189, 195, 199));
        tketerangan.setBorder(null);
        tketerangan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tketeranganFocusGained(evt);
            }
        });
        tketerangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tketeranganMouseClicked(evt);
            }
        });
        jPanel1.add(tketerangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 550, 50));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 550, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(189, 195, 199));
        jLabel3.setText("Uraian Pemasukan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(189, 195, 199));
        jLabel4.setText("Jumlah");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, -1, -1));

        tjumlah.setBackground(new java.awt.Color(44, 62, 80));
        tjumlah.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        tjumlah.setForeground(new java.awt.Color(189, 195, 199));
        tjumlah.setBorder(null);
        tjumlah.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tjumlahFocusGained(evt);
            }
        });
        tjumlah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tjumlahMouseClicked(evt);
            }
        });
        tjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjumlahActionPerformed(evt);
            }
        });
        tjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tjumlahKeyTyped(evt);
            }
        });
        jPanel1.add(tjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 170, 340, 50));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, 340, 10));

        bkembali.setBackground(new java.awt.Color(189, 195, 199));
        bkembali.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        bkembali.setForeground(new java.awt.Color(44, 62, 80));
        bkembali.setText("KEMBALI");
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });
        jPanel1.add(bkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 530, 240, 60));

        bsimpan.setBackground(new java.awt.Color(189, 195, 199));
        bsimpan.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        bsimpan.setForeground(new java.awt.Color(44, 62, 80));
        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 250, 240, 60));

        bedit.setBackground(new java.awt.Color(189, 195, 199));
        bedit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        bedit.setForeground(new java.awt.Color(44, 62, 80));
        bedit.setText("UBAH");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        jPanel1.add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 320, 240, 60));

        breset.setBackground(new java.awt.Color(189, 195, 199));
        breset.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        breset.setForeground(new java.awt.Color(44, 62, 80));
        breset.setText("RESET");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });
        jPanel1.add(breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 460, 240, 60));

        bhapus.setBackground(new java.awt.Color(189, 195, 199));
        bhapus.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        bhapus.setForeground(new java.awt.Color(44, 62, 80));
        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 390, 240, 60));

        tbl_masuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_masukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_masuk);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 950, 340));

        jButton1.setBackground(new java.awt.Color(136, 0, 0));
        jButton1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton1.setText("X");
        jButton1.setAlignmentX(0.5F);
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 70, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(189, 195, 199));
        jLabel5.setText("PENCARIAN : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, -1, -1));

        tcari.setBackground(new java.awt.Color(44, 62, 80));
        tcari.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        tcari.setForeground(new java.awt.Color(189, 195, 199));
        tcari.setBorder(null);
        tcari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tcariFocusGained(evt);
            }
        });
        tcari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tcariMouseClicked(evt);
            }
        });
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcariKeyReleased(evt);
            }
        });
        jPanel1.add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 740, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, 740, 10));

        jButton2.setBackground(new java.awt.Color(189, 195, 199));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(44, 62, 80));
        jButton2.setText("REFRESH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 630, 90, 40));

        jLabel6.setBackground(new java.awt.Color(44, 62, 80));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(189, 195, 199));
        jLabel6.setText("Total Pemasukan :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, -1, -1));

        lmasuk.setBackground(new java.awt.Color(44, 62, 80));
        lmasuk.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lmasuk.setForeground(new java.awt.Color(189, 195, 199));
        lmasuk.setText("Rp. 100.000.000");
        jPanel1.add(lmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ttanggalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ttanggalFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ttanggalFocusGained

    private void ttanggalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttanggalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ttanggalMouseClicked

    private void tketeranganFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tketeranganFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tketeranganFocusGained

    private void tketeranganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tketeranganMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tketeranganMouseClicked

    private void tjumlahFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tjumlahFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tjumlahFocusGained

    private void tjumlahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tjumlahMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tjumlahMouseClicked

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        // TODO add your handling code here:
//        utama futama = new utama();
//        futama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bkembaliActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        reset();
        bsimpan.setEnabled(true);
    }//GEN-LAST:event_bresetActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        if (ttanggal.getText().isEmpty() || tketerangan.getText().isEmpty() || tjumlah.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !");
        }else if(!tjumlah.getText().matches("[0-9]*")){
            JOptionPane.showMessageDialog(null, "JUMLAH HARUS ANGKA !");
        }else {
            try {
                st = cn.createStatement();
                st.executeUpdate("INSERT INTO tbl_keuangan (tanggal,keterangan,masuk,keluar,status,id_user)VALUES('"+ttanggal.getText()+"','"+tketerangan.getText()+"','"+tjumlah.getText()+"','0','pemasukan','"+iduser+"')");
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                tampildata();
                reset();
                masuk();
                tketerangan.requestFocus();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void tjumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tjumlahKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_TAB) ))){
            evt.consume();
        }
    }//GEN-LAST:event_tjumlahKeyTyped

    private void tjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjumlahActionPerformed

    private void ttanggalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttanggalKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ttanggalKeyReleased

    private void tbl_masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_masukMouseClicked
        // TODO add your handling code here:
        bsimpan.setEnabled(false);
        bhapus.setEnabled(true);
        bedit.setEnabled(true);
        ttanggal.setText(tabModel.getValueAt(tbl_masuk.getSelectedRow(), 1)+"");
        tketerangan.setText(tabModel.getValueAt(tbl_masuk.getSelectedRow(), 3)+"");
        tjumlah.setText(tabModel.getValueAt(tbl_masuk.getSelectedRow(), 4)+"");
        
    }//GEN-LAST:event_tbl_masukMouseClicked

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
         try {
            int jawab = 0;
            if ((jawab = JOptionPane.showConfirmDialog(null, "Anda yakin akan menghapus data ini ?","Konfirmasi", JOptionPane.YES_NO_OPTION))==0) {
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM tbl_keuangan WHERE id='"+tabModel.getValueAt(tbl_masuk.getSelectedRow(), 0)+"'");
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DIHAPUS");
                tampildata();
                reset();
                masuk();
                bsimpan.setEnabled(true);
                tketerangan.requestFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:
        if (ttanggal.getText().isEmpty() ||tketerangan.getText().isEmpty() || tjumlah.getText().isEmpty()  ) {
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA!");
            tketerangan.requestFocus();
        }else{
            try {
                st = cn.createStatement();
                st.executeUpdate("UPDATE tbl_keuangan SET tanggal ='"+ttanggal.getText()+"',keterangan = '"+tketerangan.getText()+"', masuk = '"+tjumlah.getText()+"' WHERE id = '"+tabModel.getValueAt(tbl_masuk.getSelectedRow(), 0)+"'");
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUBAH");
                tampildata();
                reset();
                masuk();
                bsimpan.setEnabled(true);
                tketerangan.requestFocus();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_beditActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       login flogin = new login();
        flogin.dispose();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    private void tcariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tcariFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariFocusGained

    private void tcariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcariMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariMouseClicked

    private void tcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyReleased
        // TODO add your handling code here:
        try {
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tbl_keuangan WHERE id_user = '"+iduser+"' AND status = 'pemasukan' AND keterangan LIKE '%"+tcari.getText()+"%'");
            while(rs.next()){
                Object[] data = {
                    rs.getInt("id"),
                    rs.getDate("tanggal"),
                    rs.getTime("waktu"),
                    rs.getString("keterangan"),
                    rs.getInt("masuk")
                };
                tabModel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tcariKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tcariKeyReleased(null);
        tcari.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        iduser=args[0];
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemasukan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkembali;
    private javax.swing.JButton breset;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lmasuk;
    private javax.swing.JTable tbl_masuk;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField tjumlah;
    private javax.swing.JTextField tketerangan;
    private javax.swing.JTextField ttanggal;
    // End of variables declaration//GEN-END:variables
}
