/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JOptionPane;

/**
 *
 * @author JamilahLKM
 */
public class utama extends javax.swing.JFrame {
 
    public static String iduser;
    public String tmp_id[];
    /**
     * Creates new form utama
     */
    public utama() {
        initComponents();
        login flogin = new login();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bpemasukan = new javax.swing.JButton();
        blaporan = new javax.swing.JButton();
        bpengeluaran = new javax.swing.JButton();
        blogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setForeground(new java.awt.Color(189, 195, 199));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bpemasukan.setBackground(new java.awt.Color(189, 195, 199));
        bpemasukan.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        bpemasukan.setForeground(new java.awt.Color(44, 62, 80));
        bpemasukan.setText("INPUT PEMASUKAN KEUANGAN");
        bpemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpemasukanActionPerformed(evt);
            }
        });
        jPanel1.add(bpemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 490, 100));

        blaporan.setBackground(new java.awt.Color(189, 195, 199));
        blaporan.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        blaporan.setForeground(new java.awt.Color(44, 62, 80));
        blaporan.setText("LAPORAN KEUANGAN");
        blaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blaporanActionPerformed(evt);
            }
        });
        jPanel1.add(blaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 490, 100));

        bpengeluaran.setBackground(new java.awt.Color(189, 195, 199));
        bpengeluaran.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        bpengeluaran.setForeground(new java.awt.Color(44, 62, 80));
        bpengeluaran.setText("INPUT PENGELUARAN KEUANGAN");
        bpengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpengeluaranActionPerformed(evt);
            }
        });
        jPanel1.add(bpengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 490, 100));

        blogout.setBackground(new java.awt.Color(189, 195, 199));
        blogout.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        blogout.setForeground(new java.awt.Color(44, 62, 80));
        blogout.setText("LOGOUT");
        blogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogoutActionPerformed(evt);
            }
        });
        jPanel1.add(blogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 490, 100));

        jLabel1.setBackground(new java.awt.Color(44, 62, 80));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(189, 195, 199));
        jLabel1.setText("APLKASI PENGELOLA KEUANGAN SEHARI-HARI ANDA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jButton1.setBackground(new java.awt.Color(136, 0, 0));
        jButton1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton1.setText("X");
        jButton1.setAlignmentX(0.5F);
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 70, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogoutActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showConfirmDialog(null, "Yakin akan keluar dari Aplikasi Ini");
        int jawab = 0;
        if ((jawab = JOptionPane.showConfirmDialog(null, "Anda yakin akan keluar dari Aplikasi ini ?","Konfirmasi", JOptionPane.YES_NO_CANCEL_OPTION))==0) {
            login flogin = new login();
            JOptionPane.showMessageDialog(null, "LOGOUT Berhasil");
            flogin.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_blogoutActionPerformed

    private void bpengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpengeluaranActionPerformed
        // TODO add your handling code here:
        tmp_id = new String[1];
        tmp_id[0] = iduser;
        pengeluaran.main(tmp_id);
//        pengeluaran fkeluar = new pengeluaran();
//        fkeluar.luser.setText(luser.getText());
//        fkeluar.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_bpengeluaranActionPerformed

    private void bpemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpemasukanActionPerformed
        // TODO add your handling code here:
        tmp_id = new String[1];
        tmp_id[0] = iduser;
        pemasukan.main(tmp_id);
//        this.setVisible(false);
    }//GEN-LAST:event_bpemasukanActionPerformed

    private void blaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blaporanActionPerformed
        // TODO add your handling code here:
        tmp_id = new String[1];
        tmp_id[0] = iduser;
        laporan.main(tmp_id);
//        this.setVisible(false);
    }//GEN-LAST:event_blaporanActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        iduser=args[0];
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blaporan;
    private javax.swing.JButton blogout;
    private javax.swing.JButton bpemasukan;
    private javax.swing.JButton bpengeluaran;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
